- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - include: tasks/node-setup.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/git-setup.yml
    - include: tasks/obsidian.yml
    - include: tasks/m1.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nvim-setup.yml