- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - include_tasks: "{{ item }}"
      with_fileglob:
        - tasks/*.yml
      # always is a special word that will preserve the tags from the included tasks
      tags: always
