- name: Installing stow
  package:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow
- name: Installing neovim
  package:
    name: neovim
    state: present
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:pawk3k/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
