- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Install neovim
  ansible.builtin.package:
    name: neovim
    state: present
  tags:
    - neovim
- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 1
  package: 
    name:
      luarocks
  tags:
    - install
    - neovim

